"""u-blox-specific CatSocks driver configuration."""

SOCKET_IDS = tuple(range(7))  # SARA-R4 socket identifiers 0..6
MAX_PARALLEL_OPENS = 2
TCP_READ_CHUNK = 512
TCP_WRITE_CHUNK = 512
DNS_TIMEOUT = 30.0
OPEN_TIMEOUT = 12.0
SOCKET_WAIT_TIMEOUT = 120.0
COMMAND_TIMEOUT = 12.0
TCP_IDLE_TIMEOUT = 10.0
HEX_MODE = True

UDP_MAX_PAYLOAD = 512
UDP_READ_CHUNK = 512
